language: node_js
node_js:
  - "4.4"
addons:
    code_climate:
        repo_token: b16005c65c4a904a8b055753c3ea9b259282b51e47b8acb9b8b6b592367525a8
before_script:
  - cp ./config/server.example.json ./config/server.json
after_script:
  - codeclimate-test-reporter < lcov.info
