#!/usr/bin/env node
/**
 * Generate a stakeholder-ready summary from a comparison report.
 * Reads report.json and outputs a clean markdown summary suitable for email/Teams.
 *
 * Usage:
 *   node scripts/summary.js [path/to/report.json]
 *   npm run summary -- inbox/output/report.json
 */

import fs from 'node:fs'
import path from 'node:path'

const reportPath = process.argv[2] || 'inbox/output/report.json'

if (!fs.existsSync(reportPath)) {
  console.error(`Report not found: ${reportPath}`)
  console.error('Run a comparison first, then pass the path to report.json')
  process.exit(1)
}

const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'))
const s = report.summary
const triage = report.triage || { structural: [], substantive: [], cosmetic: [], global_patterns: [] }
const pages = report.pages || []

const lines = []

// Header
lines.push('# Document Comparison Summary')
lines.push('')
lines.push(`**Left:** ${path.basename(report.left)}  `)
lines.push(`**Right:** ${path.basename(report.right)}  `)
lines.push(`**Date:** ${new Date(report.generated_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`)
lines.push('')

// Executive summary
if (s.identical) {
  lines.push('The two documents are **identical** — no differences found.')
} else {
  lines.push(`The documents **differ**. ${s.total_changed} of ${Math.max(s.left_page_count, s.right_page_count)} pages have changes.`)
  if (!s.page_count_match) {
    lines.push(`The revised document has ${s.right_page_count} pages (was ${s.left_page_count}).`)
  }
}
lines.push('')

// Structural changes
if (triage.structural.length > 0) {
  lines.push('## Structural Changes')
  lines.push('')
  for (const item of triage.structural) {
    const pg = pages.find(p => p.page === item.page)
    const textPreview = pg?.page_text ? pg.page_text.substring(0, 150).replace(/\n/g, ' ').trim() : ''
    lines.push(`- **${item.reason}**${textPreview ? `: "${textPreview}..."` : ''}`)
  }
  lines.push('')
}

// Substantive changes
if (triage.substantive.length > 0) {
  lines.push('## Key Changes')
  lines.push('')
  for (const item of triage.substantive) {
    const pg = pages.find(p => p.page === item.page)
    const diffs = (pg?.text_diff_lines || [])
      .filter(l => (l.startsWith('+') || l.startsWith('-')) && !l.startsWith('--- ') && !l.startsWith('+++ '))
      .slice(0, 4)
    const label = pg?.left_page != null && pg?.right_page != null
      ? (pg.left_page === pg.right_page ? `Page ${pg.left_page}` : `L${pg.left_page}→R${pg.right_page}`)
      : `Page ${item.page}`
    lines.push(`- **${label}**: ${item.reason}`)
    if (diffs.length > 0) {
      for (const d of diffs) {
        lines.push(`  - \`${d}\``)
      }
    }
  }
  lines.push('')
}

// Cosmetic summary
if (triage.cosmetic.length > 0) {
  lines.push('## Cosmetic Changes')
  lines.push('')
  // Describe global patterns instead of listing every page
  if (triage.global_patterns && triage.global_patterns.length > 0) {
    for (const gp of triage.global_patterns) {
      const desc = gp.pattern.map(l => l.replace(/^[-+]/, '').trim()).filter(Boolean).slice(0, 2).join(', ')
      lines.push(`- **${gp.count} pages** with recurring change: ${desc}`)
    }
  } else {
    lines.push(`${triage.cosmetic.length} pages with cosmetic-only changes (dates, copyright years, page numbers).`)
  }
  lines.push('')
}

// Metadata
if (report.metadata_diff && Object.keys(report.metadata_diff).length > 0) {
  lines.push('## Metadata')
  lines.push('')
  for (const [key, vals] of Object.entries(report.metadata_diff)) {
    lines.push(`- **${key}**: ${vals.left} → ${vals.right}`)
  }
  lines.push('')
}

lines.push('---')
lines.push(`*Generated by pdf-compare skill on ${new Date(report.generated_at).toLocaleDateString('en-GB')}*`)

const output = lines.join('\n')
console.log(output)

// Also write to file next to the report
const outPath = path.join(path.dirname(reportPath), 'summary.md')
fs.writeFileSync(outPath, output, 'utf8')
console.error(`\nWritten to: ${outPath}`)
