name: CI

on: [push, pull_request]
jobs:
  build:
    name: Run CI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "16.14.x"

      - name: Install node dependencies
        run: npm i

      - name: Run unit tests
        run: |
          cp ./config/.env-example .env
          npm run test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=defra
            -Dsonar.projectKey=DEFRA_fmp-app
            -Dsonar.exclusions=**/__tests__/**, **/node_modules/**, **/test/**, **/test-output/**, /test/**, **/*.spec.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.javascript.exclusions=**/node_modules/**, **/test/**, **/test-output/**, **/server/dist/**, **/server/src/**
            -Dsonar.cpd.exclusions=server/routes/**, server/views/**