name: Pre Release Version

on:
  workflow_dispatch:
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
           
      - run: git config --global user.email "Mark.Fee@defra.gov.uk"
      - run: git config --global user.name "Mark Fee"      
      - run: npm version prerelease --preid=pre -m "Set Version to %s"
      - run: git push
      - run: git push --tags
